# Generated by Django 2.2.3 on 2019-07-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190712_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpeppar',
            name='uuid_field',
        ),
    ]
