# Generated by Django 2.2.3 on 2019-07-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userpeppar_uuid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpeppar',
            name='test',
            field=models.CharField(default='1', max_length=1),
            preserve_default=False,
        ),
    ]
