# Generated by Django 2.2.3 on 2019-07-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userpeppar_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpeppar',
            name='test',
            field=models.TextField(editable=False),
        ),
    ]
