# Generated by Django 2.2.3 on 2019-07-14 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190714_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpeppar',
            name='test',
        ),
        migrations.AddField(
            model_name='userpeppar',
            name='timestamp_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
