# Generated by Django 2.2.3 on 2019-07-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userpepparrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpepparrelation',
            name='pepparrelation',
        ),
        migrations.RemoveField(
            model_name='userpepparrelation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPeppar',
        ),
        migrations.DeleteModel(
            name='UserPepparRelation',
        ),
    ]
