# Generated by Django 2.2.3 on 2019-08-01 23:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PepparType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PERSON', 'Person'), ('ENTITY', 'Entity'), ('PROPERTY', 'Property'), ('PLAN', 'Plan'), ('ACTION', 'Action'), ('RESULT', 'Result')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Peppar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, editable=False, max_length=120)),
                ('person_firstname', models.CharField(blank=True, max_length=50)),
                ('person_lastname', models.CharField(blank=True, max_length=100)),
                ('person_email', models.EmailField(blank=True, max_length=254)),
                ('person_cellphonenumber', models.CharField(blank=True, max_length=25)),
                ('entity_name', models.CharField(blank=True, max_length=120)),
                ('entity_orgnr', models.CharField(blank=True, max_length=25)),
                ('property_streetname', models.CharField(blank=True, max_length=120)),
                ('property_streetnumber', models.CharField(blank=True, max_length=10)),
                ('property_zipcode', models.CharField(blank=True, max_length=20)),
                ('property_city', models.CharField(blank=True, max_length=80)),
                ('property_country', models.CharField(blank=True, max_length=80)),
                ('plan_headline', models.CharField(blank=True, max_length=300)),
                ('plan_description', models.TextField(blank=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peppar_base.PepparType')),
            ],
        ),
    ]
