# Generated by Django 2.2.3 on 2019-07-11 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peppar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(blank=True, choices=[('A', 'Person'), ('B', 'Entity'), ('C', 'Property'), ('D', 'Plan'), ('E', 'Action'), ('F', 'Result')], max_length=1)),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
