# Generated by Django 2.2.4 on 2019-08-03 18:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peppar',
            name='specific_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
