# Generated by Django 2.2.4 on 2019-08-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peppar',
            options={'ordering': ['type']},
        ),
    ]
