# Generated by Django 2.2.3 on 2019-07-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peppar',
            name='contact_email',
            field=models.EmailField(default='arne@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
