# Generated by Django 2.2.3 on 2019-07-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0002_auto_20190715_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peppar',
            old_name='uuid_field',
            new_name='uuid',
        ),
    ]
