# Generated by Django 2.2.4 on 2019-08-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0002_peppar_specific_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peppar',
            name='description',
        ),
    ]
