# Generated by Django 2.2.3 on 2019-07-14 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0002_peppar_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peppar',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='peppar',
            name='person_cellphonenumber',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='peppar',
            name='person_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='peppar',
            name='person_firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='peppar',
            name='person_lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='peppar',
            name='type',
            field=models.CharField(choices=[('PERSON', 'Person'), ('ENTITY', 'Entity'), ('PROPERTY', 'Property'), ('PLAN', 'Plan'), ('ACTION', 'Action'), ('RESULT', 'Result')], max_length=8),
        ),
        migrations.AlterField(
            model_name='peppar',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
