# Generated by Django 2.2.4 on 2019-08-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0003_remove_peppar_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peppar',
            name='nameA_meaning',
        ),
        migrations.AlterField(
            model_name='peppar',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peppar_type', to='catalog.PepparType'),
        ),
    ]
