# Generated by Django 2.2.4 on 2019-08-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0004_auto_20190809_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peppar',
            name='nameB_meaning',
        ),
    ]
