# Generated by Django 2.2.4 on 2019-08-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0005_remove_peppar_nameb_meaning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peppar',
            name='question_meaning',
        ),
    ]
