# Generated by Django 2.2.3 on 2019-07-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='uuid_field',
            new_name='uuid',
        ),
    ]
