# Generated by Django 2.2.3 on 2019-07-09 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
