# Generated by Django 2.2.4 on 2019-08-28 22:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACOV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('dateA', models.DateTimeField(blank=True, null=True)),
                ('dateB', models.DateTimeField(blank=True, null=True)),
                ('idcode', models.CharField(blank=True, max_length=25)),
                ('question', models.BooleanField(blank=True, null=True)),
                ('specific_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PACOVSubType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CoreType')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('dateA', models.DateTimeField(blank=True, null=True)),
                ('dateB', models.DateTimeField(blank=True, null=True)),
                ('idcode', models.CharField(blank=True, max_length=25)),
                ('question', models.BooleanField(blank=True, null=True)),
                ('specific_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('pacovA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacovA', to='pacovbase.PACOV')),
                ('pacovB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacovB', to='pacovbase.PACOV')),
                ('subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PACOVSubType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CoreRelationType')),
            ],
            options={
                'ordering': ['type'],
                'unique_together': {('pacovA', 'pacovB', 'type')},
            },
        ),
    ]
