# Generated by Django 2.2.4 on 2019-08-19 23:05

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('pacovbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('dateA', models.DateTimeField(blank=True, null=True)),
                ('dateB', models.DateTimeField(blank=True, null=True)),
                ('idcode', models.CharField(blank=True, max_length=25)),
                ('question', models.BooleanField(blank=True, null=True)),
                ('specific_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('pepparA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepparA', to='pacovbase.PACOV')),
                ('pepparB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepparB', to='pacovbase.PACOV')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_type', to='catalog.RelationType')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
