# Generated by Django 2.2.4 on 2019-08-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190828_1153'),
        ('pacovbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacov',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PACOVSubType'),
        ),
        migrations.AddField(
            model_name='relation',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PACOVSubType'),
        ),
    ]
