# Generated by Django 2.2.4 on 2019-08-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('pacovbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('pacovA', 'pacovB', 'type')},
        ),
    ]
