# Generated by Django 2.2.4 on 2019-08-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacovbase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='subtype',
        ),
    ]
