# Generated by Django 2.2.4 on 2019-08-28 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacovbase', '0002_auto_20190828_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacov',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PACOVType'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.RelationType'),
        ),
    ]
