# Generated by Django 2.2.4 on 2019-08-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacovbase', '0002_remove_relation_subtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacov',
            old_name='subtype',
            new_name='category',
        ),
    ]
