# Generated by Django 2.2.4 on 2019-08-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacovbase', '0003_auto_20190828_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacov',
            options={'ordering': ['category']},
        ),
        migrations.RemoveField(
            model_name='pacov',
            name='type',
        ),
    ]
