# Generated by Django 2.2.4 on 2019-08-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacovbase', '0004_auto_20190828_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacov',
            old_name='dateA',
            new_name='ended',
        ),
        migrations.RenameField(
            model_name='pacov',
            old_name='dateB',
            new_name='started',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='dateA',
            new_name='ended',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='dateB',
            new_name='started',
        ),
    ]
