# Generated by Django 2.2.4 on 2019-09-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacovbase', '0006_auto_20190909_1236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pacov',
            unique_together=set(),
        ),
    ]
