# Generated by Django 2.2.4 on 2019-09-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190830_1304'),
        ('pacovbase', '0007_auto_20190909_1237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pacov',
            unique_together={('category', 'idcode')},
        ),
    ]
