# Generated by Django 2.2.4 on 2019-09-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190830_1304'),
        ('pacovbase', '0009_auto_20190909_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.CoreRelationType'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pacov',
            unique_together={('category', 'idcode')},
        ),
    ]
