# Generated by Django 2.2.4 on 2019-09-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacovbase', '0012_auto_20190909_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pacov',
            unique_together=set(),
        ),
    ]
