# Generated by Django 2.2.4 on 2019-09-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacovbase', '0013_auto_20190909_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={},
        ),
    ]
