# Generated by Django 2.2.3 on 2019-07-11 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peppar_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PepparRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('pepparA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepparA', to='peppar_base.Peppar')),
                ('pepparB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepparB', to='peppar_base.Peppar')),
            ],
        ),
    ]
