# Generated by Django 2.2.3 on 2019-07-15 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_relational', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepparrelation',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pepparrelation',
            name='timestamp_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pepparrelation',
            name='type_name',
            field=models.CharField(choices=[('Styreleder', 'Styreleder'), ('Styremedlem', 'Styremedlem')], default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pepparrelation',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
    ]
