# Generated by Django 2.2.3 on 2019-07-14 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_relational', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepparrelation',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
