# Generated by Django 2.2.4 on 2019-08-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_relational', '0003_relation_specific_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_type', to='catalog.RelationType'),
        ),
    ]
