# Generated by Django 2.2.3 on 2019-07-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0003_auto_20190728_2159'),
        ('user_views', '0008_auto_20190728_2221'),
        ('peppar_relational', '0003_auto_20190728_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PepparRelation',
            new_name='Relation',
        ),
    ]
