# Generated by Django 2.2.4 on 2019-08-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_relational', '0004_auto_20190809_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='dateA_meaning',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='dateB_meaning',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='idcode_meaning',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='question_meaning',
        ),
    ]
