# Generated by Django 2.2.4 on 2019-08-28 22:51

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pacovrelation_type', models.CharField(choices=[('PER-OBJ', '(PER-OBJ)'), ('PER-ACT', '(PER-ACT)'), ('PER-CON', '(PER-CON)'), ('OBJ-VAL', '(OBJ-VAL)'), ('ACT-VAL', '(ACT-VAL)'), ('ACT-OBJ', '(ACT-OBJ)'), ('CON-ACT', '(CON-ACT)'), ('CON-VAL', '(CON-VAL)'), ('CON-OBJ', '(CON-OBJ)'), ('CON-CON', '(CON-CON)')], max_length=7)),
                ('sub_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pacov_type', models.CharField(choices=[('PERSON', 'PERSON'), ('ACTION', 'ACTION'), ('CONCEPT', 'CONCEPT'), ('OBJECT', 'OBJECT'), ('VALUE', 'VALUE')], max_length=8)),
                ('sub_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pacov_type'],
            },
        ),
        migrations.CreateModel(
            name='DefaultScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('defaultscheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.DefaultScheme')),
                ('maintype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CoreType')),
            ],
        ),
        migrations.CreateModel(
            name='PACOVSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('defaultscheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.DefaultScheme')),
                ('maintype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CoreType')),
            ],
        ),
    ]
