# Generated by Django 2.2.3 on 2019-08-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PepparType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PERSON', 'Person Type'), ('ENTITY', 'Entity Type'), ('PROPERTY', 'Property Type'), ('PLAN', 'Plan Type'), ('ACTION', 'Action Type'), ('RESULT', 'Result Type')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PER-PER', 'PER-PER'), ('PLA-PLA', 'PLA-PLA'), ('PER-ENT', 'PER-ENT'), ('PER-PLA', 'PER-PLA'), ('ENT-PLA', 'ENT-PLA')], max_length=7)),
            ],
        ),
    ]
