# Generated by Django 2.2.4 on 2019-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peppartype',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='relationtype',
            options={'ordering': ['type']},
        ),
        migrations.AlterField(
            model_name='peppartype',
            name='type',
            field=models.CharField(choices=[('PERSON', 'PERSON'), ('ACTION', 'ACTION'), ('CONCEPT', 'CONCEPT'), ('OBJECT', 'OBJECT'), ('STATUS', 'STATUS')], max_length=8),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='type',
            field=models.CharField(choices=[('PER-ENT', '(PER-ENT)'), ('PER-PRO', '(PER-PRO)'), ('PER-PLA', '(PER-PLA)'), ('PER-ACT', '(PER-ACT)'), ('PER-RES', '(PER-RES)'), ('ENT-PRO', '(ENT-PRO)'), ('ENT-PLA', '(ENT-PLA)'), ('ENT-ACT', '(ENT-ACT)'), ('ENT-RES', '(ENT-RES)'), ('PRO-PLA', '(PRO-PLA)'), ('PRO-ACT', '(PRO-ACT)'), ('PRO-RES', '(PRO-RES)'), ('PLA-ACT', '(PLA-ACT)'), ('PLA-RES', '(PLA-RES)'), ('ACT-RES', '(ACT-RES)'), ('PER-PER', '(PER-PER)'), ('ENT-ENT', '(ENT-ENT)'), ('PRO-PRO', '(PRO-PRO)'), ('PLA-PLA', '(PLA-PLA)'), ('ACT-ACT', '(ACT-ACT)'), ('RES-RES', '(RES-RES)')], max_length=7),
        ),
    ]
