# Generated by Django 2.2.4 on 2019-08-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacovtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
