# Generated by Django 2.2.4 on 2019-08-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacovbase', '0001_initial'),
        ('catalog', '0002_auto_20190828_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PACOVSubType',
            new_name='Category',
        ),
    ]
