# Generated by Django 2.2.4 on 2019-08-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190816_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peppartype',
            name='type',
            field=models.CharField(choices=[('PERSON', 'PERSON'), ('ACTION', 'ACTION'), ('CONCEPT', 'CONCEPT'), ('OBJECT', 'OBJECT'), ('VALUE', 'VALUE')], max_length=8),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='type',
            field=models.CharField(choices=[('PER-OBJ', '(PER-OBJ)'), ('PER-ACT', '(PER-ACT)'), ('PER-CON', '(PER-CON)'), ('OBJ-STA', '(OBJ-STA)'), ('ACT-STA', '(ACT-STA)'), ('ACT-OBJ', '(ACT-OBJ)'), ('CON-ACT', '(CON-ACT)'), ('CON-STA', '(CON-STA)'), ('CON-OBJ', '(CON-OBJ)')], max_length=7),
        ),
    ]
