# Generated by Django 2.2.4 on 2019-08-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190819_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationtype',
            name='type',
            field=models.CharField(choices=[('PER-OBJ', '(PER-OBJ)'), ('PER-ACT', '(PER-ACT)'), ('PER-CON', '(PER-CON)'), ('OBJ-VAL', '(OBJ-VAL)'), ('ACT-VAL', '(ACT-VAL)'), ('ACT-OBJ', '(ACT-OBJ)'), ('CON-ACT', '(CON-ACT)'), ('CON-VAL', '(CON-VAL)'), ('CON-OBJ', '(CON-OBJ)')], max_length=7),
        ),
    ]
