# Generated by Django 2.2.4 on 2019-08-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190828_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultscheme',
            old_name='scheme',
            new_name='defaultscheme',
        ),
    ]
