# Generated by Django 2.2.4 on 2019-08-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190828_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationSubType',
        ),
    ]
