# Generated by Django 2.2.4 on 2019-08-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190828_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultscheme',
            old_name='defaultscheme',
            new_name='scheme',
        ),
    ]
