# Generated by Django 2.2.4 on 2019-08-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_base', '0002_auto_20190816_1343'),
        ('catalog', '0004_auto_20190819_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PepparType',
            new_name='PACOVType',
        ),
    ]
