# Generated by Django 2.2.4 on 2019-08-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190828_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacovtype',
            options={'ordering': ['pacov_type']},
        ),
        migrations.AlterModelOptions(
            name='relationtype',
            options={'ordering': ['relation_type']},
        ),
        migrations.RenameField(
            model_name='pacovtype',
            old_name='type',
            new_name='pacov_type',
        ),
        migrations.RenameField(
            model_name='relationtype',
            old_name='type',
            new_name='relation_type',
        ),
    ]
