# Generated by Django 2.2.4 on 2019-08-29 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190829_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corerelationtype',
            name='categoryA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coretypeA', to='catalog.CoreType'),
        ),
        migrations.AlterField(
            model_name='corerelationtype',
            name='categoryB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coretypeB', to='catalog.CoreType'),
        ),
    ]
