# Generated by Django 2.2.4 on 2019-08-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190829_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corerelationtype',
            options={},
        ),
        migrations.RemoveField(
            model_name='corerelationtype',
            name='pacovrelation_type',
        ),
    ]
