# Generated by Django 2.2.4 on 2019-08-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190829_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corerelationtype',
            old_name='categoryA',
            new_name='coretypeA',
        ),
        migrations.RenameField(
            model_name='corerelationtype',
            old_name='categoryB',
            new_name='coretypeB',
        ),
    ]
