# Generated by Django 2.2.4 on 2019-08-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190829_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='corerelationtype',
            name='defaultscheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.DefaultScheme'),
        ),
    ]
