# Generated by Django 2.2.4 on 2019-09-09 19:47

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190830_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coretype',
            options={},
        ),
        migrations.AlterField(
            model_name='defaultscheme',
            name='scheme',
            field=jsonfield.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
