# Generated by Django 2.2.4 on 2019-09-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20190909_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultScheme',
            new_name='Schema',
        ),
    ]
