# Generated by Django 2.2.4 on 2019-09-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190918_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='scheme',
            new_name='specific_data_schema',
        ),
    ]
