# Generated by Django 2.2.4 on 2019-09-18 12:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_category_specific_data_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='corerelationtype',
            name='specific_data_schema',
            field=jsonfield.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
