# Generated by Django 2.2.4 on 2019-09-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_corerelationtype_specific_data_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='corerelationtype',
            name='schema',
        ),
    ]
