# Generated by Django 2.2.3 on 2019-07-14 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peppar_relational', '0002_auto_20190714_2317'),
        ('peppar_base', '0003_auto_20190714_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPepparRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('0', 'Me'), ('1', 'Full info'), ('2', 'Limited info'), ('3', 'Hidden')], max_length=1)),
                ('timestamp_updated', models.DateTimeField(editable=False)),
                ('pepparrelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peppar_relational.PepparRelation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPeppar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('0', 'Me'), ('1', 'Full info'), ('2', 'Limited info'), ('3', 'Hidden')], max_length=1)),
                ('timestamp_updated', models.DateTimeField(editable=False)),
                ('peppar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peppar_base.Peppar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
