# Generated by Django 2.2.3 on 2019-07-15 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peppar_relational', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peppar_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PepparRelationAsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(blank=True, choices=[('0', 'Me'), ('1', 'Full info'), ('2', 'Limited info'), ('3', 'Hidden')], max_length=1)),
                ('timestamp_updated', models.DateTimeField(editable=False)),
                ('pepparrelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peppar_relational.PepparRelation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PepparAsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(blank=True, choices=[('0', 'Me'), ('1', 'Full info'), ('2', 'Limited info'), ('3', 'Hidden')], max_length=1)),
                ('timestamp_updated', models.DateTimeField(editable=False)),
                ('peppar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peppar_base.Peppar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
