# Generated by Django 2.2.4 on 2019-08-20 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacovbase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_views', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationinsight',
            unique_together={('user', 'relation')},
        ),
    ]
