# Generated by Django 2.2.3 on 2019-07-15 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepparasuser',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='pepparasuser',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pepparasuser',
            name='level',
            field=models.CharField(choices=[('0', 'Myself'), ('1', 'Full sight'), ('2', 'Limited sight'), ('3', 'Hidden')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pepparasuser',
            name='timestamp_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
