# Generated by Django 2.2.3 on 2019-07-15 19:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_relational', '0002_auto_20190714_2317'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_views', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPepparRelation',
            new_name='PepparRelationAsUser',
        ),
    ]
