# Generated by Django 2.2.4 on 2019-09-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationinsight',
            name='level',
            field=models.CharField(choices=[('1', 'My'), ('2', 'Close'), ('3', 'Distant')], max_length=1),
        ),
    ]
