# Generated by Django 2.2.4 on 2019-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0002_auto_20190820_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationinsight',
            name='level',
            field=models.CharField(blank=True, choices=[('1', 'My'), ('2', 'Close'), ('3', 'Distant')], max_length=1),
        ),
    ]
