# Generated by Django 2.2.3 on 2019-07-15 19:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peppar_base', '0003_auto_20190714_2317'),
        ('user_views', '0002_auto_20190715_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPeppar',
            new_name='PepparAsUser',
        ),
    ]
