# Generated by Django 2.2.3 on 2019-07-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0003_auto_20190715_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepparasuser',
            name='level',
            field=models.CharField(choices=[('0', 'Me'), ('1', 'My'), ('2', 'Close'), ('3', 'Distant')], max_length=1),
        ),
    ]
