# Generated by Django 2.2.3 on 2019-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0004_auto_20190728_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepparrelationasuser',
            name='level',
            field=models.CharField(blank=True, choices=[('0', 'Me'), ('1', 'My'), ('2', 'Close'), ('3', 'Distant')], max_length=1),
        ),
    ]
