# Generated by Django 2.2.3 on 2019-07-28 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peppar_base', '0003_auto_20190728_2159'),
        ('user_views', '0006_auto_20190728_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PepparAsUser',
            new_name='PepparInsight',
        ),
    ]
