# Generated by Django 2.2.3 on 2019-07-28 22:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppar_relational', '0003_auto_20190728_2159'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_views', '0007_auto_20190728_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PepparRelationAsUser',
            new_name='RelationInsight',
        ),
    ]
