# Generated by Django 2.2.3 on 2019-07-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0008_auto_20190728_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pepparinsight',
            name='name',
        ),
    ]
