# Generated by Django 2.2.3 on 2019-07-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0010_remove_relationinsight_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationinsight',
            old_name='pepparrelation',
            new_name='relation',
        ),
    ]
